const fs = require('fs');
const path = require('path');

const requiredFiles = [
  'README.md',
  'package.json',
  'scripts/turbo-doctor.js',
  'docs/TURBOREPO.md',
  'turbo.json',
  'index.html',
  'assets/config.js',
  'assets/integrations.js',
  'assets/store.css',
  'assets/store.js',
  'docs/INTEGRATIONS.md',
  'supabase/migrations/202605130001_storefront_core.sql',
  'vercel.json',
  'CLAUDE.md',
  '.github/workflows/check.yml',
  '.github/pull_request_template.md',
  '.github/ISSUE_TEMPLATE/ai-agent-task.md',
  'shopify-ruby/Gemfile',
  'shopify-ruby/.env.example',
  'shopify-ruby/config/shopify_context.rb',
  'shopify-ruby/lib/forma_shopify/admin_client.rb',
  'shopify-ruby/lib/forma_shopify/storefront_client.rb',
  'shopify-ruby/scripts/list_products.rb',
  'shopify-ruby/README.md',
  'docs/UPSTREAM_SHOPIFY_RUBY.md',
  'scripts/prepare-shopify-upstream.sh',
  'scripts/github-plain-diff.js',
  'docs/GITHUB_PLAIN_DIFFS.md',
  'scripts/smoke-static.js',
  'scripts/smoke-app.js',
  'packages/storefront-data/package.json',
  'packages/storefront-data/index.js',
  'packages/config/package.json',
  'packages/config/index.js',
  'packages/ui/package.json',
  'packages/ui/index.js',
  'apps/docs/package.json',
  'apps/docs/index.html',
  'apps/storefront/package.json',
  'apps/storefront/index.html',
  'docs/GO_LIVE_CHECKLIST.md',

  'shopify-theme/README.md',
  'shopify-theme/Gemfile',
  'shopify-theme/spec/spec_helper.rb',
  'shopify-theme/spec/helpers/html_helper.rb',
  'shopify-theme/spec/helpers/i18n_helper.rb',
  'shopify-theme/spec/i18n_validity_spec.rb',
  'shopify-theme/spec/html_validity_spec.rb',
  'shopify-theme/locales/en.default.json',
  'shopify-theme/locales/es.default.json',
  'shopify-theme/assets/forma-theme.css.liquid',
  'shopify-theme/assets/forma-theme.js',
  'shopify-theme/assets/timber.js.liquid',
  'shopify-theme/assets/ajax-cart.js.liquid',
  'shopify-theme/assets/gift-card.scss.liquid',
  'shopify-theme/snippets/breadcrumb.liquid',
  'shopify-theme/snippets/collection-sorting.liquid',
  'shopify-theme/snippets/onboarding-empty-collection.liquid',
  'shopify-theme/snippets/onboarding-featured-collections.liquid',
  'shopify-theme/snippets/comment.liquid',
  'shopify-theme/snippets/oldIE-js.liquid',
  'shopify-theme/snippets/ajax-cart-template.liquid',
  'shopify-theme/templates/gift_card.liquid',
  'shopify-theme/layout/theme.liquid',
  'shopify-theme/snippets/site-header.liquid',
  'shopify-theme/snippets/site-footer.liquid',
  'shopify-theme/snippets/product-card.liquid',
  'shopify-theme/spec/theme_structure_spec.rb',
  'shopify-theme/templates/404.liquid',
  'shopify-theme/templates/article.liquid',
  'shopify-theme/templates/blog.liquid',
  'shopify-theme/templates/cart.liquid',
  'shopify-theme/templates/collection.liquid',
  'shopify-theme/templates/collection.list.liquid',
  'shopify-theme/templates/index.liquid',
  'shopify-theme/templates/list-collections.liquid',
  'shopify-theme/templates/page.contact.liquid',
  'shopify-theme/templates/page.liquid',
  'shopify-theme/templates/product.liquid',
  'shopify-theme/templates/search.liquid',
  'shopify-theme/templates/customers/account.liquid',
  'shopify-theme/templates/customers/addresses.liquid',
  'shopify-theme/templates/customers/login.liquid',
  'shopify-theme/templates/customers/order.liquid',
  'shopify-theme/templates/customers/register.liquid',
  'shopify-theme/config.yml',
  'shopify-theme/config/settings_schema.json',
  'shopify-theme/config/settings_data.json',
];

const emptyFiles = requiredFiles.filter((file) => {
  const fullPath = path.join(process.cwd(), file);
  return !fs.existsSync(fullPath) || fs.readFileSync(fullPath, 'utf8').trim().length === 0;
});

if (emptyFiles.length) {
  console.error(`Empty or missing required files:\n${emptyFiles.map((file) => `- ${file}`).join('\n')}`);
  process.exit(1);
}

console.log(`Verified ${requiredFiles.length} required files contain content.`);
