create table if not exists public.store_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  payload jsonb not null default '{}'::jsonb,
  page_path text,
  user_agent text,
  created_at timestamptz not null default now(),
  constraint store_events_event_name_length check (char_length(event_name) between 1 and 80),
  constraint store_events_page_path_length check (page_path is null or char_length(page_path) <= 2048),
  constraint store_events_user_agent_length check (user_agent is null or char_length(user_agent) <= 512),
  constraint store_events_payload_is_object check (jsonb_typeof(payload) = 'object')
);

create table if not exists public.newsletter_signups (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text not null default 'forma-storefront',
  created_at timestamptz not null default now(),
  constraint newsletter_signups_email_length check (char_length(email) between 3 and 254),
  constraint newsletter_signups_email_shape check (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

alter table public.store_events enable row level security;
alter table public.newsletter_signups enable row level security;

drop policy if exists "Allow anonymous storefront event inserts" on public.store_events;
create policy "Allow anonymous storefront event inserts"
  on public.store_events
  for insert
  to anon
  with check (
    char_length(event_name) between 1 and 80
    and jsonb_typeof(payload) = 'object'
    and (page_path is null or char_length(page_path) <= 2048)
    and (user_agent is null or char_length(user_agent) <= 512)
  );

drop policy if exists "Allow anonymous newsletter inserts" on public.newsletter_signups;
create policy "Allow anonymous newsletter inserts"
  on public.newsletter_signups
  for insert
  to anon
  with check (
    source = 'forma-storefront'
    and char_length(email) between 3 and 254
    and email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
  );
