create table if not exists public.store_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  payload jsonb not null default '{}'::jsonb,
  page_path text,
  user_agent text,
  created_at timestamptz not null default now()
);

create table if not exists public.newsletter_signups (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text not null default 'forma-storefront',
  created_at timestamptz not null default now()
);

alter table public.store_events enable row level security;
alter table public.newsletter_signups enable row level security;

drop policy if exists "Allow anonymous storefront event inserts" on public.store_events;
create policy "Allow anonymous storefront event inserts"
  on public.store_events
  for insert
  to anon
  with check (true);

drop policy if exists "Allow anonymous newsletter inserts" on public.newsletter_signups;
create policy "Allow anonymous newsletter inserts"
  on public.newsletter_signups
  for insert
  to anon
  with check (source = 'forma-storefront');
